packages:
  - docs
  - packages/*

catalog:
  '@clack/prompts': ^0.11.0
  '@deviltea/eslint-config': 6.0.0
  '@deviltea/tsconfig': 0.0.8
  '@shikijs/vitepress-twoslash': ^3.9.2
  '@standard-schema/spec': ^1.0.0
  '@types/node': ^24.10.1
  '@vitest/coverage-v8': ^4.0.10
  bumpp: ^10.3.1
  eslint: ^9.39.1
  lint-staged: ^16.2.6
  pathe: ^2.0.3
  pkg-size: ^2.4.0
  publint: ^0.3.15
  rimraf: ^6.1.0
  simple-git-hooks: ^2.13.1
  tsdown: ^0.16.7
  tsx: ^4.20.6
  type-fest: ^5.0.1
  typescript: ^5.9.3
  vite: ^7.1.1
  vitepress: ^2.0.0-alpha.9
  vitepress-plugin-group-icons: ^1.3.6
  vitest: ^4.0.10
  vue: ^3.5.18
  vue-tsc: ^3.0.5
  zx: ^8.8.5
