packages:
  - docs
  - 'packages/*'

catalog:
  '@clack/prompts': ^0.11.0
  '@deviltea/eslint-config': 5.0.0
  '@deviltea/tsconfig': 0.0.8
  '@shikijs/vitepress-twoslash': ^3.9.2
  '@types/node': ^22.13.5
  '@vitest/coverage-v8': ^3.2.4
  bumpp: ^10.2.2
  eslint: ^9.33.0
  lint-staged: ^16.1.5
  pathe: ^2.0.3
  pkg-size: ^2.4.0
  publint: ^0.3.12
  rimraf: ^6.0.1
  simple-git-hooks: ^2.13.1
  tsx: ^4.20.3
  typescript: ^5.9.2
  unbuild: ^3.6.0
  vite: ^7.1.1
  vitepress: ^2.0.0-alpha.9
  vitepress-plugin-group-icons: ^1.3.6
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-tsc: ^3.0.5
  zx: ^8.8.0
