import type { DocsNavigationItem } from './navigation'
import { transformerTwoslash } from '@shikijs/vitepress-twoslash'
import { defineConfig } from 'vitepress'
import { graphvizMarkdownPlugin } from 'vitepress-plugin-graphviz'
import { groupIconMdPlugin as MarkdownItGroupIcon } from 'vitepress-plugin-group-icons'
import { createDocsSidebar, docsNav } from './navigation'

type GraphvizMarkdownIt = Parameters<typeof graphvizMarkdownPlugin>[0]

/** Generated by `pnpm docs:api:update`; narrative page identity lives in `docs/_meta/pages.ts`. */
const apiReferenceItems: DocsNavigationItem[] = [
	// #region generated-api-sidebar
	{ text: 'Overview', link: '/api/overview' },
	{ text: 'Primitives', link: '/api/primitives' },
	{ text: 'String Formats', link: '/api/formats' },
	{ text: 'Structures', link: '/api/structures' },
	{ text: 'Transforms', link: '/api/transforms' },
	{ text: 'Helpers & Utilities', link: '/api/helpers' },
	// #endregion generated-api-sidebar
]

// https://vitepress.dev/reference/site-config
export default defineConfig({
	base: '/valchecker/',
	title: 'valchecker',
	description: 'Modular runtime validation for TypeScript with full type inference',
	themeConfig: {
		nav: docsNav,
		sidebar: createDocsSidebar(apiReferenceItems),

		socialLinks: [
			{ icon: 'github', link: 'https://github.com/DevilTea/valchecker' },
		],
	},

	markdown: {
		config: async (md) => {
			md.use(MarkdownItGroupIcon)
			// VitePress 2 alpha.17 exposes its parser as MarkdownItAsync because highlighting may
			// return a promise, while graphviz 0.1.0 still types the same plugin surface as
			// synchronous MarkdownIt. The plugin's documented integration is this async config hook;
			// keep the mismatch isolated here and let the production docs build prove rendering.
			await graphvizMarkdownPlugin(md as unknown as GraphvizMarkdownIt)
		},
		codeTransformers: [
			transformerTwoslash(),
		],
		languages: ['js', 'jsx', 'ts', 'tsx'],
	},
})
